// WREAL model automatically generated by Arana Bottom-up Designer 
// 
// Module name: svwphy_lp4x5_cmn_wphy_lp4x5_refgen_hv_v3_PAM4 
// Copyright: Orora Design Technologies, Inc., Issaquah, WA. 
// All rights reserved. 
// Model Generated Time: Tue Aug 30 21:18:47 2022

// Arana Version 7.0.0  
// TBVAM Version 8.05_09_14_2021  
// 
// Orora Design Technologies (R) Arana Model Generator (R) Arana 
// Copyright (C) 1998-2014 Orora Design Technologies, Inc. All rights reserved worldwide. 
// Orora, Arana are registered trademarks of Orora Design Technologies, Inc.  All others  
// are the property of their respective holders. 
//
// Arana Technologies and Arana GUI, Arana Flow are protected by U.S. Patents pending. 
//
// Notice: This model has been generated using Arana evaluation license and should not be 
// used for any other purpose except the evaluation of Arana for purchasing. 




// Model Generation Date: 2022-08-30; Time: 21:18:09

// User Name: xindil

// OS Info
// 	 name: Linux
// 	 architecture: amd64
// 	 version: 3.10.0-1160.11.1.el7.x86_64

// aranaBMP version: 7.0.0, build time May 03, 2022 (09:30 AM PDT by ycai79)

// Project Library Info
// 	 library OCD_SR_UCIe
// 	 cell wphy_lp4x5_cmn_wphy_lp4x5_refgen_hv_v3_PAM4
// 	 schematic version:  Unknown
// 	 view sv
// 	 aranaBMP running directory /home/xindil/rail/lpddr/arana/OCD_SR_UCIe

// Pin table information 
// 1 name: Dout\<2\>; type: Large_Analog-Signal
//    probe: Zero Current; source: Voltage
// 2 name: Dout\<1\>; type: Large_Analog-Signal
//    probe: Zero Current; source: Voltage
// 3 name: Dout\<0\>; type: Large_Analog-Signal
//    probe: Zero Current; source: Voltage
// 4 name: PAM4_en; type: Configure
// 5 name: cal0\<3\>; type: Configure
// 6 name: cal0\<2\>; type: Configure
// 7 name: cal0\<1\>; type: Configure
// 8 name: cal0\<0\>; type: Configure
// 9 name: cal1\<3\>; type: Configure
// 10 name: cal1\<2\>; type: Configure
// 11 name: cal1\<1\>; type: Configure
// 12 name: cal1\<0\>; type: Configure
// 13 name: cal2\<3\>; type: Configure
// 14 name: cal2\<2\>; type: Configure
// 15 name: cal2\<1\>; type: Configure
// 16 name: cal2\<0\>; type: Configure
// 17 name: cal_ck; type: VSource
// 18 name: cal_dir\<2\>; type: Configure
// 19 name: cal_dir\<1\>; type: Configure
// 20 name: cal_dir\<0\>; type: Configure
// 21 name: cal_en; type: VSource
// 22 name: ena_hv; type: Configure
// 23 name: hiz_hv; type: Configure
// 24 name: pwr_hv\<1\>; type: VSource
// 25 name: pwr_hv\<0\>; type: VSource
// 26 name: vdda1p2; type: VSupply
// 27 name: vddq; type: VSupply
// 28 name: vref\<2\>; type: Large_Analog-Signal
//    probe: Zero Current; source: Voltage
// 29 name: vref\<1\>; type: Large_Analog-Signal
//    probe: Zero Current; source: Voltage
// 30 name: vref\<0\>; type: Large_Analog-Signal
//    probe: Zero Current; source: Voltage
// 31 name: vref_ctrl_hv\<7\>; type: Configure
// 32 name: vref_ctrl_hv\<6\>; type: Configure
// 33 name: vref_ctrl_hv\<5\>; type: Configure
// 34 name: vref_ctrl_hv\<4\>; type: Configure
// 35 name: vref_ctrl_hv\<3\>; type: Configure
// 36 name: vref_ctrl_hv\<2\>; type: Configure
// 37 name: vref_ctrl_hv\<1\>; type: Configure
// 38 name: vref_ctrl_hv\<0\>; type: Configure
// 39 name: vss; type: Gnd

// Corner Infomation 
// 	 corner 1
// 		 temperature 27
// 		 process 
// 			 "/home/lab.apps/vlsiapps/kits/tsmc/N28HPC+RF/tsmcN28/../models/spectre/toplevel.scs" section=top_tt
// 		 variable 
// 			 procID: 0

`ifndef ODT_SYSTEMVERILOG_TS
  `timescale 1ps / 100fs
`endif

module wphy_lp4x5_cmn_wphy_lp4x5_refgen_hv_v3_PAM4( Dout ,PAM4_en ,cal0 ,cal1 ,cal2 ,cal_ck ,cal_dir ,cal_en ,ena_hv ,hiz_hv ,pwr_hv ,vdda1p2 ,vddq ,vref ,vref_ctrl_hv ,vss );
`ifdef ODT_SYSTEMVERILOG_TS
  timeunit 1ps;
  timeprecision 100fs;
`endif
input cal_ck;
input cal_en;
input [1:0] pwr_hv;
input vdda1p2;
input vddq;
input vss;
input PAM4_en;
input [3:0] cal0;
input [3:0] cal1;
input [3:0] cal2;
input [2:0] cal_dir;
input ena_hv;
input hiz_hv;
input [7:0] vref_ctrl_hv;
output [2:0] Dout;
output [2:0] vref;
reg flagcdf_0; 
reg BDout__2__intd; 
reg BDout__2__0,BDout__2__1,BDout__2__2,BDout__2__3,BDout__2__4,BDout__2__5,BDout__2__6,BDout__2__7,BDout__2__8,BDout__2__9;
reg BDout__2__10,BDout__2__11,BDout__2__12,BDout__2__13,BDout__2__14,BDout__2__15; 
reg out_Dout__2__logic;
reg BDout__1__intd; 
reg BDout__1__0,BDout__1__1,BDout__1__2,BDout__1__3,BDout__1__4,BDout__1__5,BDout__1__6,BDout__1__7,BDout__1__8,BDout__1__9;
reg BDout__1__10,BDout__1__11,BDout__1__12,BDout__1__13,BDout__1__14,BDout__1__15; 
reg out_Dout__1__logic;
reg BDout__0__intd; 
reg BDout__0__0,BDout__0__1,BDout__0__2,BDout__0__3,BDout__0__4,BDout__0__5,BDout__0__6,BDout__0__7,BDout__0__8,BDout__0__9;
reg BDout__0__10,BDout__0__11,BDout__0__12,BDout__0__13,BDout__0__14,BDout__0__15; 
reg out_Dout__0__logic;
reg Bvref__2__intd; 
reg Bvref__2__0,Bvref__2__1,Bvref__2__2,Bvref__2__3,Bvref__2__4,Bvref__2__5,Bvref__2__6,Bvref__2__7,Bvref__2__8,Bvref__2__9;
reg Bvref__2__10,Bvref__2__11,Bvref__2__12,Bvref__2__13,Bvref__2__14,Bvref__2__15; 
reg out_vref__2__logic;
reg Bvref__1__intd; 
reg Bvref__1__0,Bvref__1__1,Bvref__1__2,Bvref__1__3,Bvref__1__4,Bvref__1__5,Bvref__1__6,Bvref__1__7,Bvref__1__8,Bvref__1__9;
reg Bvref__1__10,Bvref__1__11,Bvref__1__12,Bvref__1__13,Bvref__1__14,Bvref__1__15; 
reg out_vref__1__logic;
reg Bvref__0__intd; 
reg Bvref__0__0,Bvref__0__1,Bvref__0__2,Bvref__0__3,Bvref__0__4,Bvref__0__5,Bvref__0__6,Bvref__0__7,Bvref__0__8,Bvref__0__9;
reg Bvref__0__10,Bvref__0__11,Bvref__0__12,Bvref__0__13,Bvref__0__14,Bvref__0__15; 
reg out_vref__0__logic;
initial begin 
  end 
initial begin 
  end
initial begin 
   BDout__2__intd=0; 
   BDout__1__intd=0; 
   BDout__0__intd=0; 
   Bvref__2__intd=0; 
   Bvref__1__intd=0; 
   Bvref__0__intd=0; 
  end
 always @( PAM4_en   or cal0[3]   or cal0[2]   or cal0[1]   or cal0[0]   or cal1[3]   or cal1[2]   or cal1[1]   or cal1[0]   or cal2[3]   or cal2[2]   or cal2[1]   or cal2[0]   or cal_dir[2]   or cal_dir[1]   or cal_dir[0]   or ena_hv   or hiz_hv   or vref_ctrl_hv[7]   or vref_ctrl_hv[6]   or vref_ctrl_hv[5]   or vref_ctrl_hv[4]   or vref_ctrl_hv[3]   or vref_ctrl_hv[2]   or vref_ctrl_hv[1]   or vref_ctrl_hv[0]  ) begin 
    flagcdf_0=0;
 	case ({cal0[3],cal0[2],cal0[1],cal0[0],cal1[3],cal1[2],cal1[1],cal1[0],cal2[3],cal2[2],cal2[1],cal2[0],cal_dir[2],cal_dir[1],cal_dir[0],vref_ctrl_hv[7],vref_ctrl_hv[6],vref_ctrl_hv[5],vref_ctrl_hv[4],vref_ctrl_hv[3],vref_ctrl_hv[2],vref_ctrl_hv[1],vref_ctrl_hv[0],PAM4_en,ena_hv,hiz_hv}) 
	26'b00000000000000011000010000: begin 
        BDout__2__intd= 0; 
        BDout__1__intd= 0; 
        BDout__0__intd= 0; 
        Bvref__2__intd= 1; 
        Bvref__1__intd= 1; 
        Bvref__0__intd= 1; 
	end 
	26'b00000000000000011000010001: begin 
        BDout__2__intd= 0; 
        BDout__1__intd= 0; 
        BDout__0__intd= 0; 
        Bvref__2__intd= 0; 
        Bvref__1__intd= 0; 
        Bvref__0__intd= 0; 
	end 
	26'b00000000000000011000010010: begin 
        BDout__2__intd= 0; 
        BDout__1__intd= 0; 
        BDout__0__intd= 0; 
        Bvref__2__intd= 1; 
        Bvref__1__intd= 0; 
        Bvref__0__intd= 1; 
	end 
	26'b00000000000000011000010011: begin 
        BDout__2__intd= 0; 
        BDout__1__intd= 0; 
        BDout__0__intd= 0; 
        Bvref__2__intd= 0; 
        Bvref__1__intd= 0; 
        Bvref__0__intd= 0; 
	end 
	26'b00000000000000011000010100: begin 
        BDout__2__intd= 0; 
        BDout__1__intd= 0; 
        BDout__0__intd= 0; 
        Bvref__2__intd= 1; 
        Bvref__1__intd= 1; 
        Bvref__0__intd= 1; 
	end 
	26'b00000000000000011000010101: begin 
        BDout__2__intd= 0; 
        BDout__1__intd= 0; 
        BDout__0__intd= 0; 
        Bvref__2__intd= 0; 
        Bvref__1__intd= 0; 
        Bvref__0__intd= 0; 
	end 
	26'b00000000000000011000010110: begin 
        BDout__2__intd= 0; 
        BDout__1__intd= 0; 
        BDout__0__intd= 0; 
        Bvref__2__intd= 0; 
        Bvref__1__intd= 0; 
        Bvref__0__intd= 0; 
	end 
	26'b00000000000000011000010111: begin 
        BDout__2__intd= 0; 
        BDout__1__intd= 0; 
        BDout__0__intd= 0; 
        Bvref__2__intd= 0; 
        Bvref__1__intd= 0; 
        Bvref__0__intd= 0; 
	end 
	26'b00000000000000001100100000: begin 
        BDout__2__intd= 0; 
        BDout__1__intd= 0; 
        BDout__0__intd= 0; 
        Bvref__2__intd= 1; 
        Bvref__1__intd= 1; 
        Bvref__0__intd= 1; 
	end 
	26'b00000000000000001100100001: begin 
        BDout__2__intd= 0; 
        BDout__1__intd= 0; 
        BDout__0__intd= 0; 
        Bvref__2__intd= 0; 
        Bvref__1__intd= 0; 
        Bvref__0__intd= 0; 
	end 
	26'b00000000000000001100100010: begin 
        BDout__2__intd= 0; 
        BDout__1__intd= 0; 
        BDout__0__intd= 0; 
        Bvref__2__intd= 1; 
        Bvref__1__intd= 0; 
        Bvref__0__intd= 1; 
	end 
	26'b00000000000000001100100011: begin 
        BDout__2__intd= 0; 
        BDout__1__intd= 0; 
        BDout__0__intd= 0; 
        Bvref__2__intd= 0; 
        Bvref__1__intd= 0; 
        Bvref__0__intd= 0; 
	end 
	26'b00000000000000001100100100: begin 
        BDout__2__intd= 0; 
        BDout__1__intd= 0; 
        BDout__0__intd= 0; 
        Bvref__2__intd= 1; 
        Bvref__1__intd= 1; 
        Bvref__0__intd= 1; 
	end 
	26'b00000000000000001100100101: begin 
        BDout__2__intd= 0; 
        BDout__1__intd= 0; 
        BDout__0__intd= 0; 
        Bvref__2__intd= 0; 
        Bvref__1__intd= 0; 
        Bvref__0__intd= 0; 
	end 
	26'b00000000000000001100100110: begin 
        BDout__2__intd= 0; 
        BDout__1__intd= 0; 
        BDout__0__intd= 0; 
        Bvref__2__intd= 0; 
        Bvref__1__intd= 0; 
        Bvref__0__intd= 0; 
	end 
	26'b00000000000000001100100111: begin 
        BDout__2__intd= 0; 
        BDout__1__intd= 0; 
        BDout__0__intd= 0; 
        Bvref__2__intd= 0; 
        Bvref__1__intd= 0; 
        Bvref__0__intd= 0; 
	end 
	default: begin 
	flagcdf_0=1;
        BDout__2__intd= 1'bx;
        BDout__1__intd= 1'bx;
        BDout__0__intd= 1'bx;
        Bvref__2__intd= 1'bx;
        Bvref__1__intd= 1'bx;
        Bvref__0__intd= 1'bx;
	end 
	endcase 
`ifdef CONTROL_CONFIGURE_X_Z_CHECKING
 if( ($realtime>0) && (flagcdf_0)) begin
  $display("Arana Model Check Warning in Module %m: some configuration variables and/or control variables are \"X\" or \"Z\".");
 end
`endif
`ifdef INVALID_CONFIGURATION_CHECKING
 if(($realtime>0) && (flagcdf_0)) begin
  $display("Arana Model Check Error in Module %m: not entering any valid configuration. The previous valid configuration is used instead. The current invalid configuration is:");
  $display(" cal0[3]=%d  cal0[2]=%d  cal0[1]=%d  cal0[0]=%d  cal1[3]=%d  cal1[2]=%d  cal1[1]=%d  cal1[0]=%d  cal2[3]=%d  cal2[2]=%d  cal2[1]=%d  cal2[0]=%d  cal_dir[2]=%d  cal_dir[1]=%d  cal_dir[0]=%d  vref_ctrl_hv[7]=%d  vref_ctrl_hv[6]=%d  vref_ctrl_hv[5]=%d  vref_ctrl_hv[4]=%d  vref_ctrl_hv[3]=%d  vref_ctrl_hv[2]=%d  vref_ctrl_hv[1]=%d  vref_ctrl_hv[0]=%d  PAM4_en=%d  ena_hv=%d  hiz_hv=%d ", cal0[3], cal0[2], cal0[1], cal0[0], cal1[3], cal1[2], cal1[1], cal1[0], cal2[3], cal2[2], cal2[1], cal2[0], cal_dir[2], cal_dir[1], cal_dir[0], vref_ctrl_hv[7], vref_ctrl_hv[6], vref_ctrl_hv[5], vref_ctrl_hv[4], vref_ctrl_hv[3], vref_ctrl_hv[2], vref_ctrl_hv[1], vref_ctrl_hv[0], PAM4_en, ena_hv, hiz_hv);
  $display("The valid configurations are:");
  $display(" cal0[3]:Low  cal0[2]:Low  cal0[1]:Low  cal0[0]:Low  cal1[3]:Low  cal1[2]:Low  cal1[1]:Low  cal1[0]:Low  cal2[3]:Low  cal2[2]:Low  cal2[1]:Low  cal2[0]:Low  cal_dir[2]:Low  cal_dir[1]:Low  cal_dir[0]:Low  vref_ctrl_hv[7]:High  vref_ctrl_hv[6]:High  vref_ctrl_hv[5]:Low  vref_ctrl_hv[4]:Low  vref_ctrl_hv[3]:Low  vref_ctrl_hv[2]:Low  vref_ctrl_hv[1]:High  vref_ctrl_hv[0]:Low  PAM4_en:Low  ena_hv:Low  hiz_hv:Low ");
  $display(" cal0[3]:Low  cal0[2]:Low  cal0[1]:Low  cal0[0]:Low  cal1[3]:Low  cal1[2]:Low  cal1[1]:Low  cal1[0]:Low  cal2[3]:Low  cal2[2]:Low  cal2[1]:Low  cal2[0]:Low  cal_dir[2]:Low  cal_dir[1]:Low  cal_dir[0]:Low  vref_ctrl_hv[7]:High  vref_ctrl_hv[6]:High  vref_ctrl_hv[5]:Low  vref_ctrl_hv[4]:Low  vref_ctrl_hv[3]:Low  vref_ctrl_hv[2]:Low  vref_ctrl_hv[1]:High  vref_ctrl_hv[0]:Low  PAM4_en:Low  ena_hv:Low  hiz_hv:High ");
  $display(" cal0[3]:Low  cal0[2]:Low  cal0[1]:Low  cal0[0]:Low  cal1[3]:Low  cal1[2]:Low  cal1[1]:Low  cal1[0]:Low  cal2[3]:Low  cal2[2]:Low  cal2[1]:Low  cal2[0]:Low  cal_dir[2]:Low  cal_dir[1]:Low  cal_dir[0]:Low  vref_ctrl_hv[7]:High  vref_ctrl_hv[6]:High  vref_ctrl_hv[5]:Low  vref_ctrl_hv[4]:Low  vref_ctrl_hv[3]:Low  vref_ctrl_hv[2]:Low  vref_ctrl_hv[1]:High  vref_ctrl_hv[0]:Low  PAM4_en:Low  ena_hv:High  hiz_hv:Low ");
  $display(" cal0[3]:Low  cal0[2]:Low  cal0[1]:Low  cal0[0]:Low  cal1[3]:Low  cal1[2]:Low  cal1[1]:Low  cal1[0]:Low  cal2[3]:Low  cal2[2]:Low  cal2[1]:Low  cal2[0]:Low  cal_dir[2]:Low  cal_dir[1]:Low  cal_dir[0]:Low  vref_ctrl_hv[7]:High  vref_ctrl_hv[6]:High  vref_ctrl_hv[5]:Low  vref_ctrl_hv[4]:Low  vref_ctrl_hv[3]:Low  vref_ctrl_hv[2]:Low  vref_ctrl_hv[1]:High  vref_ctrl_hv[0]:Low  PAM4_en:Low  ena_hv:High  hiz_hv:High ");
  $display(" cal0[3]:Low  cal0[2]:Low  cal0[1]:Low  cal0[0]:Low  cal1[3]:Low  cal1[2]:Low  cal1[1]:Low  cal1[0]:Low  cal2[3]:Low  cal2[2]:Low  cal2[1]:Low  cal2[0]:Low  cal_dir[2]:Low  cal_dir[1]:Low  cal_dir[0]:Low  vref_ctrl_hv[7]:High  vref_ctrl_hv[6]:High  vref_ctrl_hv[5]:Low  vref_ctrl_hv[4]:Low  vref_ctrl_hv[3]:Low  vref_ctrl_hv[2]:Low  vref_ctrl_hv[1]:High  vref_ctrl_hv[0]:Low  PAM4_en:High  ena_hv:Low  hiz_hv:Low ");
  $display(" cal0[3]:Low  cal0[2]:Low  cal0[1]:Low  cal0[0]:Low  cal1[3]:Low  cal1[2]:Low  cal1[1]:Low  cal1[0]:Low  cal2[3]:Low  cal2[2]:Low  cal2[1]:Low  cal2[0]:Low  cal_dir[2]:Low  cal_dir[1]:Low  cal_dir[0]:Low  vref_ctrl_hv[7]:High  vref_ctrl_hv[6]:High  vref_ctrl_hv[5]:Low  vref_ctrl_hv[4]:Low  vref_ctrl_hv[3]:Low  vref_ctrl_hv[2]:Low  vref_ctrl_hv[1]:High  vref_ctrl_hv[0]:Low  PAM4_en:High  ena_hv:Low  hiz_hv:High ");
  $display(" cal0[3]:Low  cal0[2]:Low  cal0[1]:Low  cal0[0]:Low  cal1[3]:Low  cal1[2]:Low  cal1[1]:Low  cal1[0]:Low  cal2[3]:Low  cal2[2]:Low  cal2[1]:Low  cal2[0]:Low  cal_dir[2]:Low  cal_dir[1]:Low  cal_dir[0]:Low  vref_ctrl_hv[7]:High  vref_ctrl_hv[6]:High  vref_ctrl_hv[5]:Low  vref_ctrl_hv[4]:Low  vref_ctrl_hv[3]:Low  vref_ctrl_hv[2]:Low  vref_ctrl_hv[1]:High  vref_ctrl_hv[0]:Low  PAM4_en:High  ena_hv:High  hiz_hv:Low ");
  $display(" cal0[3]:Low  cal0[2]:Low  cal0[1]:Low  cal0[0]:Low  cal1[3]:Low  cal1[2]:Low  cal1[1]:Low  cal1[0]:Low  cal2[3]:Low  cal2[2]:Low  cal2[1]:Low  cal2[0]:Low  cal_dir[2]:Low  cal_dir[1]:Low  cal_dir[0]:Low  vref_ctrl_hv[7]:High  vref_ctrl_hv[6]:High  vref_ctrl_hv[5]:Low  vref_ctrl_hv[4]:Low  vref_ctrl_hv[3]:Low  vref_ctrl_hv[2]:Low  vref_ctrl_hv[1]:High  vref_ctrl_hv[0]:Low  PAM4_en:High  ena_hv:High  hiz_hv:High ");
  $display(" cal0[3]:Low  cal0[2]:Low  cal0[1]:Low  cal0[0]:Low  cal1[3]:Low  cal1[2]:Low  cal1[1]:Low  cal1[0]:Low  cal2[3]:Low  cal2[2]:Low  cal2[1]:Low  cal2[0]:Low  cal_dir[2]:Low  cal_dir[1]:Low  cal_dir[0]:Low  vref_ctrl_hv[7]:Low  vref_ctrl_hv[6]:High  vref_ctrl_hv[5]:High  vref_ctrl_hv[4]:Low  vref_ctrl_hv[3]:Low  vref_ctrl_hv[2]:High  vref_ctrl_hv[1]:Low  vref_ctrl_hv[0]:Low  PAM4_en:Low  ena_hv:Low  hiz_hv:Low ");
  $display(" cal0[3]:Low  cal0[2]:Low  cal0[1]:Low  cal0[0]:Low  cal1[3]:Low  cal1[2]:Low  cal1[1]:Low  cal1[0]:Low  cal2[3]:Low  cal2[2]:Low  cal2[1]:Low  cal2[0]:Low  cal_dir[2]:Low  cal_dir[1]:Low  cal_dir[0]:Low  vref_ctrl_hv[7]:Low  vref_ctrl_hv[6]:High  vref_ctrl_hv[5]:High  vref_ctrl_hv[4]:Low  vref_ctrl_hv[3]:Low  vref_ctrl_hv[2]:High  vref_ctrl_hv[1]:Low  vref_ctrl_hv[0]:Low  PAM4_en:Low  ena_hv:Low  hiz_hv:High ");
  $display(" cal0[3]:Low  cal0[2]:Low  cal0[1]:Low  cal0[0]:Low  cal1[3]:Low  cal1[2]:Low  cal1[1]:Low  cal1[0]:Low  cal2[3]:Low  cal2[2]:Low  cal2[1]:Low  cal2[0]:Low  cal_dir[2]:Low  cal_dir[1]:Low  cal_dir[0]:Low  vref_ctrl_hv[7]:Low  vref_ctrl_hv[6]:High  vref_ctrl_hv[5]:High  vref_ctrl_hv[4]:Low  vref_ctrl_hv[3]:Low  vref_ctrl_hv[2]:High  vref_ctrl_hv[1]:Low  vref_ctrl_hv[0]:Low  PAM4_en:Low  ena_hv:High  hiz_hv:Low ");
  $display(" cal0[3]:Low  cal0[2]:Low  cal0[1]:Low  cal0[0]:Low  cal1[3]:Low  cal1[2]:Low  cal1[1]:Low  cal1[0]:Low  cal2[3]:Low  cal2[2]:Low  cal2[1]:Low  cal2[0]:Low  cal_dir[2]:Low  cal_dir[1]:Low  cal_dir[0]:Low  vref_ctrl_hv[7]:Low  vref_ctrl_hv[6]:High  vref_ctrl_hv[5]:High  vref_ctrl_hv[4]:Low  vref_ctrl_hv[3]:Low  vref_ctrl_hv[2]:High  vref_ctrl_hv[1]:Low  vref_ctrl_hv[0]:Low  PAM4_en:Low  ena_hv:High  hiz_hv:High ");
  $display(" cal0[3]:Low  cal0[2]:Low  cal0[1]:Low  cal0[0]:Low  cal1[3]:Low  cal1[2]:Low  cal1[1]:Low  cal1[0]:Low  cal2[3]:Low  cal2[2]:Low  cal2[1]:Low  cal2[0]:Low  cal_dir[2]:Low  cal_dir[1]:Low  cal_dir[0]:Low  vref_ctrl_hv[7]:Low  vref_ctrl_hv[6]:High  vref_ctrl_hv[5]:High  vref_ctrl_hv[4]:Low  vref_ctrl_hv[3]:Low  vref_ctrl_hv[2]:High  vref_ctrl_hv[1]:Low  vref_ctrl_hv[0]:Low  PAM4_en:High  ena_hv:Low  hiz_hv:Low ");
  $display(" cal0[3]:Low  cal0[2]:Low  cal0[1]:Low  cal0[0]:Low  cal1[3]:Low  cal1[2]:Low  cal1[1]:Low  cal1[0]:Low  cal2[3]:Low  cal2[2]:Low  cal2[1]:Low  cal2[0]:Low  cal_dir[2]:Low  cal_dir[1]:Low  cal_dir[0]:Low  vref_ctrl_hv[7]:Low  vref_ctrl_hv[6]:High  vref_ctrl_hv[5]:High  vref_ctrl_hv[4]:Low  vref_ctrl_hv[3]:Low  vref_ctrl_hv[2]:High  vref_ctrl_hv[1]:Low  vref_ctrl_hv[0]:Low  PAM4_en:High  ena_hv:Low  hiz_hv:High ");
  $display(" cal0[3]:Low  cal0[2]:Low  cal0[1]:Low  cal0[0]:Low  cal1[3]:Low  cal1[2]:Low  cal1[1]:Low  cal1[0]:Low  cal2[3]:Low  cal2[2]:Low  cal2[1]:Low  cal2[0]:Low  cal_dir[2]:Low  cal_dir[1]:Low  cal_dir[0]:Low  vref_ctrl_hv[7]:Low  vref_ctrl_hv[6]:High  vref_ctrl_hv[5]:High  vref_ctrl_hv[4]:Low  vref_ctrl_hv[3]:Low  vref_ctrl_hv[2]:High  vref_ctrl_hv[1]:Low  vref_ctrl_hv[0]:Low  PAM4_en:High  ena_hv:High  hiz_hv:Low ");
  $display(" cal0[3]:Low  cal0[2]:Low  cal0[1]:Low  cal0[0]:Low  cal1[3]:Low  cal1[2]:Low  cal1[1]:Low  cal1[0]:Low  cal2[3]:Low  cal2[2]:Low  cal2[1]:Low  cal2[0]:Low  cal_dir[2]:Low  cal_dir[1]:Low  cal_dir[0]:Low  vref_ctrl_hv[7]:Low  vref_ctrl_hv[6]:High  vref_ctrl_hv[5]:High  vref_ctrl_hv[4]:Low  vref_ctrl_hv[3]:Low  vref_ctrl_hv[2]:High  vref_ctrl_hv[1]:Low  vref_ctrl_hv[0]:Low  PAM4_en:High  ena_hv:High  hiz_hv:High ");
 end
`endif
  out_Dout__2__logic = BDout__2__intd; 
  out_Dout__1__logic = BDout__1__intd; 
  out_Dout__0__logic = BDout__0__intd; 
  out_vref__2__logic = Bvref__2__intd; 
  out_vref__1__logic = Bvref__1__intd; 
  out_vref__0__logic = Bvref__0__intd; 
 end 
 assign Dout[2] = out_Dout__2__logic;
 assign Dout[1] = out_Dout__1__logic;
 assign Dout[0] = out_Dout__0__logic;
 assign vref[2] = out_vref__2__logic;
 assign vref[1] = out_vref__1__logic;
 assign vref[0] = out_vref__0__logic;
endmodule 



