//****************************************************************************************
//
// Verilog model automatically generated by Arana Digital Model Generation
// 9.1.50 Build date 02-02-2021
// Model Method=1   Ratioless=yes   Delay=no, NewOptimization=yes
//
//
// Module name: wphy_sa_4g_2ph_pdly_no_esd_wphy_nmos_switch_PAM4
// Model Generated Time: Tue Aug 30 20:08:20 2022
//
//
// Weak Devices Removed=NONE  MaxW/LsizeFactor=100.00
//
//
// Copyright: Orora Design Technologies, Inc., Issaquah, WA.
// All rights reserved.
//
// Orora Design Technologies (R) Arana Model Generator (R) Arana
// Copyright (C) 1998-2014 Orora Design Technologies, Inc. All rights reserved worldwide.
// Orora, Arana are registered trademarks of Orora Design Technologies, Inc. All others
// are the property of their respective holders.
//
// Arana Technologies and Arana GUI, Arana Flow are protected by U.S. Patents pending.
//
// Notice: This model has been generated using Arana evaluation license and should not be
// used for any other purpose except the evaluation of Arana for purchasing.
//
// 
// // Model Generation Date: 2022-08-30; Time: 20:08:19
// 
// // User Name: xindil
// 
// // OS Info
// // 	 name: Linux
// // 	 architecture: amd64
// // 	 version: 3.10.0-1160.11.1.el7.x86_64
// 
// // aranaBMP version: 7.0.0, build time May 03, 2022 (09:30 AM PDT by ycai79)
// 
// // Project Library Info
// // 	 library OCD_SR_UCIe
// // 	 cell wphy_sa_4g_2ph_pdly_no_esd_wphy_nmos_switch_PAM4
// // 	 schematic version:  Unknown
// // 	 view sv
// // 	 aranaBMP running directory /home/xindil/rail/lpddr/arana/OCD_SR_UCIe
// 
// // Pin table information 
// //	 1name: ena; type: Logic_Data
// //	 2name: inn\<2\>; type: Logic_Data
// //	 3name: inn\<1\>; type: Logic_Data
// //	 4name: inn\<0\>; type: Logic_Data
// //	 5name: inp; type: Logic_Data
// //	 6name: out\<2\>; type: Logic_Data
// //	 7name: out\<1\>; type: Logic_Data
// //	 8name: out\<0\>; type: Logic_Data
// //	 9name: vdda; type: VSupply
// //	 10name: vss; type: Gnd
//
//****************************************************************************************

`ifndef ODT_SYSTEMVERILOG_TS
`timescale 1ps / 100fs
`endif

module wphy_sa_4g_2ph_pdly_no_esd_wphy_nmos_switch_PAM4 (ena, inn_0, inn_1, inn_2, inp, out_0, out_1, out_2, vdda, vss);
`ifdef ODT_SYSTEMVERILOG_TS
   timeunit 1ps;
   timeprecision 100fs;
`endif
   input ena;
   input real inn_0, inn_1, inn_2;
   input real inp;

   output real out_0;
   output real out_1;
   output real out_2;
   input vdda;
   input vss;


    assign out_2 = (ena)?inn_2:inp;
    assign out_1 = (ena)?inn_1:inp;
    assign out_0 = (ena)?inn_0:inp;
/*
   // start  component:0

   assign out[0] = ((!ena && inp) || (ena && inn[0]));

   assign out[2] = ((!ena && inp) || (ena && inn[2]));

   assign out[1] = ((!ena && inp) || (ena && inn[1]));

   // end  component:0
*/
endmodule // end of wphy_sa_4g_2ph_pdly_no_esd_wphy_nmos_switch_PAM4
