+define+RW_ONLY
+define+DATA_PATH
+define+TIMING_CHECK
+incdir+./
+incdir+../rtl
+incdir+./memory_controller_top
+incdir+./dfi_lpddr4_agent
+incdir+./native_agent
+incdir+./dfi_agent
./memory_controller_top/tb_csr_top.sv
../rtl/interface.sv
../rtl/refresher_pos_8.v
../rtl/bankmachine_0.v
../rtl/bankmachine_1.v
../rtl/bankmachine_2.v
../rtl/bankmachine_3.v
../rtl/bankmachine_4.v
../rtl/bankmachine_5.v
../rtl/bankmachine_6.v
../rtl/bankmachine_7.v
../rtl/crossbar_2ports.v
../rtl/DFIAdapter.v
../rtl/crossbar_2ports_wrapper.sv
../rtl/multiplexer_b8_wrapper.sv
../rtl/refresher_pos_8_wrapper.sv
../rtl/bankmachine_wrapper.sv
../rtl/mc_core.sv
../rtl/mc_top.sv
//../rtl/mosi_native.v
../rtl/multiplexer_b8.v
../rtl/tapped_delay_line.sv
../rtl/ahb.sv
../verif/mixed_phy/sram_loader.sv
