+incdir+/../../../wav-lpddr-hw/rtl/wddr
../../../wav-lpddr-hw/rtl/wddr/ddr_global_pkg.sv
../../../wav-lpddr-hw/rtl/ibex/ibex_pkg.sv
../../../wav-lpddr-hw/rtl/ahb/wav_ahb_pkg.sv
../../../wav-lpddr-hw/rtl/mcu_ibex/wav_mcu_pkg.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_fifo.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_snoop.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_dp.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_rx.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_tx.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_ahb.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_dq_csr_wrapper.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_dq_ahb_csr.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_dq_csr.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_ca_csr_wrapper.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_ca_ahb_csr.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_ca_csr.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_dfich_ahb_csr.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_dfich_csr.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_dfi_ahb_csr.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_dfi_csr.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_dfi.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_phy.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_cmn.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_cmn_ahb_csr.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_cmn_csr.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_cmn_wrapper.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_fsw_ahb_csr.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_fsw_csr.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_pmon_dig.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_pmon_freqdet.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_pi_wrapper.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_pi_match_wrapper.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_pi_b2t_dec.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_sa_2ph_pdly_no_esd_wrapper.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_dq_drvr_lpbk_wrapper.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_cke_drvr_lpbk_wrapper.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_dqs_drvr_lpbk_wrapper.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_clkmux_diff_wrapper.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_clkmux_3to1_diff_wrapper.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_2to1_wrapper.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_prog_dly_dec.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_prog_dly_se_wrapper.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_prog_dly_se_small_wrapper.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_dqs_rcvr_no_esd_wrapper.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_ctrl_csr.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_ctrl_ahb_csr.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_ctrl_plane.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_phy_1x32.sv
../../../wav-lpddr-hw/rtl/wddr/ddr_component_lib.sv

+incdir+../../../wav-lpddr-hw/rtl/ibex
../../../wav-lpddr-hw/rtl/ibex/ibex_alu.sv
../../../wav-lpddr-hw/rtl/ibex/ibex_compressed_decoder.sv
../../../wav-lpddr-hw/rtl/ibex/ibex_controller.sv
../../../wav-lpddr-hw/rtl/ibex/ibex_counter.sv
../../../wav-lpddr-hw/rtl/ibex/ibex_cs_registers.sv
../../../wav-lpddr-hw/rtl/ibex/ibex_decoder.sv
../../../wav-lpddr-hw/rtl/ibex/ibex_ex_block.sv
../../../wav-lpddr-hw/rtl/ibex/ibex_id_stage.sv
../../../wav-lpddr-hw/rtl/ibex/ibex_if_stage.sv
../../../wav-lpddr-hw/rtl/ibex/ibex_wb_stage.sv
../../../wav-lpddr-hw/rtl/ibex/ibex_load_store_unit.sv
../../../wav-lpddr-hw/rtl/ibex/ibex_multdiv_slow.sv
../../../wav-lpddr-hw/rtl/ibex/ibex_multdiv_fast.sv
../../../wav-lpddr-hw/rtl/ibex/ibex_prefetch_buffer.sv
../../../wav-lpddr-hw/rtl/ibex/ibex_fetch_fifo.sv
../../../wav-lpddr-hw/rtl/ibex/ibex_pmp.sv
../../../wav-lpddr-hw/rtl/ibex/ibex_register_file_ff.sv
../../../wav-lpddr-hw/rtl/ibex/ibex_core.sv
../../../wav-lpddr-hw/rtl/ibex/ibex_csr.sv
../../../wav-lpddr-hw/rtl/ibex/ibex_branch_predict.sv
../../../wav-lpddr-hw/rtl/ibex/prim_assert.sv

+incdir+../../../wav-lpddr-hw/rtl/ahb
../../../wav-lpddr-hw/rtl/ahb/wav_ahb.sv

+incdir+../../../wav-lpddr-hw/rtl/component
../../../wav-lpddr-hw/rtl/component/wav_component_lib.sv

+incdir+../../../wav-lpddr-hw/rtl/jtag
../../../wav-lpddr-hw/rtl/jtag/wav_jtag_lib.sv

+incdir+../../../wav-lpddr-hw/rtl/tech
../../../wav-lpddr-hw/rtl/tech/ddr_custom_lib.sv
../../../wav-lpddr-hw/rtl/tech/ddr_stdcell_lib.sv
../../../wav-lpddr-hw/rtl/tech/wav_stdcell_lib.sv
../../../wav-lpddr-hw/rtl/tech/wav_tcm_sp.sv
../../../wav-lpddr-hw/rtl/tech/wav_legacy_stdcell_lib.v

+incdir+../../../wav-lpddr-hw/rtl/mvp_pll
../../../wav-lpddr-hw/rtl/mvp_pll/mvp_fll.v
../../../wav-lpddr-hw/rtl/mvp_pll/mvp_pll_clk_control.v
../../../wav-lpddr-hw/rtl/mvp_pll/mvp_pll_dig.v
../../../wav-lpddr-hw/rtl/mvp_pll/mvp_pll_regs_top.v
../../../wav-lpddr-hw/rtl/mvp_pll/mvp_pll_sm.v
../../../wav-lpddr-hw/rtl/mvp_pll/mvp_sync_pulse.v

+incdir+../../../wav-lpddr-hw/rtl/pll_shared
../../../wav-lpddr-hw/rtl/pll_shared/wav_pll_shared_lib.v

+incdir+../../../wav-lpddr-hw/rtl/mcu_ibex
../../../wav-lpddr-hw/rtl/mcu_ibex/prim_clock_gating.sv
../../../wav-lpddr-hw/rtl/mcu_ibex/wav_mcu_ahb_csr.sv
../../../wav-lpddr-hw/rtl/mcu_ibex/wav_mcu_csr.sv
../../../wav-lpddr-hw/rtl/mcu_ibex/wav_mcuintf_ahb_csr.sv
../../../wav-lpddr-hw/rtl/mcu_ibex/wav_mcuintf_csr.sv
../../../wav-lpddr-hw/rtl/mcu_ibex/wav_mcutop_ahb_csr.sv
../../../wav-lpddr-hw/rtl/mcu_ibex/wav_mcutop_csr.sv
../../../wav-lpddr-hw/rtl/mcu_ibex/wav_mcu_ibex.sv
